version: '3.8'
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - fastapi_tutor_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: employment_exchange

  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

    volumes:
      - fastapi_tutor_rabbitdata:/var/lib/rabbitmq

  redis:
    image: redis:7.0.4
    ports:
      - 6379:6379
    restart: always

    volumes:
      - fastapi_tutor_redisdata:/usr/local/etc/redis
  app:
    container_name: fastpi-app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host '0.0.0.0' --port 8000 --reload
    restart: always
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app/src

      # db
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: employment_exchange

      # rabbitmq
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      MESSAGE_BROKER: amqp

      # redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_URL: redis://localhost:6379/0

    depends_on:
      - db
      - rabbit
      - redis

volumes:
  fastapi_tutor_pgdata: {}
  fastapi_tutor_rabbitdata: {}
  fastapi_tutor_redisdata: {}
